#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED

#define IDI_ICON_FWTOOL_MAIN    101


typedef enum
{
    IDC_HEAD = 2000,

    IDC_GROUP_DECRYPTION,
    IDC_STATIC_LABEL_DEC_INPUT,
    IDC_STATIC_LABEL_DEC_OUTPUT,
    IDC_EDIT_DEC_INPUT,
    IDC_EDIT_DEC_OUTPUT,
    IDC_BUTTON_DEC_BROWSE_INPUT_FILE,
    IDC_BUTTON_DEC_BROWSE_OUTPUT_DIR,
    IDC_BUTTON_DEC,


    IDC_GROUP_ENCRYPTION,
    IDC_STATIC_LABEL_ENC_INPUT,
    IDC_STATIC_LABEL_ENC_OUTPUT,
    IDC_EDIT_ENC_INPUT,
    IDC_EDIT_ENC_OUTPUT,
    IDC_BUTTON_ENC_BROWSE_INPUT_DIR,
    IDC_BUTTON_ENC_BROWSE_OUTPUT_FILE,
    IDC_BUTTON_ENC,


    IDC_GROUP_OPTIONS,
    IDC_STATIC_LABEL_OPT_LANGUAGE,
    IDC_COMBO_OPT_LANGUAGES,
    IDC_BUTTON_OPT_APPLY,

    IDC_GROUP_STATUS,
    IDC_STATIC_LABEL_STA_PROGRESS,
    IDC_PROGRESS_BAR_STA,


    /*
    IDC_STATIC_LABEL_OUTPUT,
    IDC_STATIC_LABEL_INPUT,
    IDC_BUTTON_BROWSE_INPUT,
    IDC_BUTTON_BROWSE_OUTPUT,
    IDC_EDIT_INPUT,
    IDC_EDIT_OUTPUT,

    IDC_GROUP_CONTROL_AND_STATUS,
    IDC_STATIC_LABEL_MODE,
    IDC_STATIC_LABEL_MODE_INFO,
    IDC_BUTTON_PROCESS,
    IDC_PROGRESS_BAR,
    IDC_STATIC_LABEL_STATUS,
    IDC_STATIC_LABEL_PROGRESS,

    IDC_GROUP_OPTIONS,
    IDC_COMBO_LANGUAGES,
    IDC_STATIC_LABEL_LANGUAGE,
    IDC_EDIT_STATUS,
    */

    IDC_BOTTOM
} GUI_IDC;

#endif // RESOURCE_H_INCLUDED
